src/objects/Student_Registration__c/Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registration</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/StudentRegistrationFormClass.cls
public class StudentRegistrationFormClass {
    @AuraEnabled
    public static void CreateStudentEntry (String studentName, String fatherName, Integer mobile, Integer fee) {
        try {
            if (studentName != null && fatherName != null && mobile != null && fee != null) {
            	Database.Insert(new Student_Registration__c (Name= studentName, Father_Name__c= fatherName, Mobile__c= mobile, Fee__c= fee));        
            }
        }
        catch (Exception e) {
            system.debug('Error in creating Student detail :: '+e.getMessage());
        }
    }
}